FROM ubuntu:22.04

# Install native build dependencies
RUN apt-get update && \
    apt-get install -y \
        build-essential \
        cmake \
        ninja-build \
        git \
        pkg-config \
        libssl-dev \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY . .

ENTRYPOINT ["/src/libgit2sharp-native/build-native-linux.sh"]
